// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package api

// Defines values for GetWeatherParamsUnit.
const (
	Imperial GetWeatherParamsUnit = "imperial"
	Metric   GetWeatherParamsUnit = "metric"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Message Error message
	Message *string `json:"message,omitempty"`
}

// WeatherResponse defines model for WeatherResponse.
type WeatherResponse struct {
	// Temperature Temperature in the area
	Temperature *float32 `json:"temperature,omitempty"`

	// TemperatureCondition Hot, cold, or moderate
	TemperatureCondition *string `json:"temperatureCondition,omitempty"`

	// Unit Temperature unit
	Unit *string `json:"unit,omitempty"`

	// WeatherCondition Rain, snow, etc
	WeatherCondition *string `json:"weatherCondition,omitempty"`
}

// GetWeatherParams defines parameters for GetWeather.
type GetWeatherParams struct {
	// Lat Latitude
	Lat float32 `form:"lat" json:"lat"`

	// Lon Longitude
	Lon float32 `form:"lon" json:"lon"`

	// Unit Temperature unit
	Unit *GetWeatherParamsUnit `form:"unit,omitempty" json:"unit,omitempty"`
}

// GetWeatherParamsUnit defines parameters for GetWeather.
type GetWeatherParamsUnit string
